shop_homepage:
    path:     /
    defaults: { _controller: ShopBundle:Default:index }


shop_details:
    path:     /details/{id}
    defaults: { _controller: ShopBundle:Default:details }

shop_addtopanier:
    path:     /panier/{id}
    defaults: { _controller: ShopBundle:Panier:addToPanier }
myproduct:
    path:     /myproduct
    defaults: { _controller: ShopBundle:Default:myproduct }
checkout:
    path:     /checkout
    defaults: { _controller: ShopBundle:Panier:checkout }
deletech:
    path:     /delete/{id}
    defaults: { _controller: ShopBundle:Panier:deletech }

orders:
    path:     /orders/{total}
    defaults: { _controller: ShopBundle:Panier:order }

